repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: nbformat-normalize
        name: nbformat-normalize
        entry: python -c "import sys, nbformat; [nbformat.write(nbformat.read(f, as_version=4), f) for f in sys.argv[1:]]"
        language: python
        files: \.ipynb$
        pass_filenames: true
        additional_dependencies: ['nbformat']

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: \.ipynb$
